### ISSUE TITLE
Symfony5 support?

### ISSUE THREAD

**Issue by itsmitul** [Liinkiing/graphql-maker-bundle#2]
Hello! Thank you for this awesome bundle. Are there plans to support Symfony 5?

**Comment by Liinkiing** [comment]
Hey! 

Glad that you're using it, I've made the changes and draft a new release: https://github.com/Liinkiing/graphql-maker-bundle/releases/tag/1.3.0

You can already `composer req liinkiing/graphql-maker-bundle` and it should be good with a version 5 of Symfony 👍 

Please tell me if it's working on your side, so I'll close the issue!
